"""init

Revision ID: 21b3b82736c3
Revises: 08a2c8b4e9b1
Create Date: 2020-07-26 22:13:25.192571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b3b82736c3'
down_revision = '08a2c8b4e9b1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
